spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.45.55:3306/master?allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    redisson:
      file: classpath:redisson.yaml
    host: 192.168.45.55
    port: 6379
    database: 0
    timeout: 10000
    jedis:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 8
        min-idle: 0
  elasticsearch:
    uris: 192.168.45.55:9200
mybatis:
  mapper-locations: classpath:/mapper/*.xml