spring:
  servlet:
    multipart:
      max-file-size: 102400MB
      max-request-size: 102400MB
      location: /Users/t3/Desktop/upload
account:
  password:
    salt: 123456
upload:
  target:
    path: /Users/t3/Desktop/save
